"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"
import { Loader2, ArrowRight } from "lucide-react"
import { signIn } from "next-auth/react"

export default function AdminSignupPage() {
  const router = useRouter(); const [loading,setLoading]=useState(false); const [error,setError]=useState("")
  const [form,setForm]=useState({companyName:"",companyEmail:"",companyPhone:"",adminName:"",username:"",password:"",confirmPassword:""})
  const set=(k:string,v:string)=>setForm({...form,[k]:v})
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError("");if(form.password!==form.confirmPassword)return setError("Passwords do not match.");setLoading(true);try{const res=await fetch(process.env.NEXT_PUBLIC_GRAPHQL_URL||"http://localhost:9000/graphql",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:`mutation RegisterAdmin($email:String!,$password:String!,$name:String!,$tenantName:String!,$companyPhone:String,$username:String,$companyEmail:String){registerAdmin(email:$email,password:$password,name:$name,tenantName:$tenantName,companyPhone:$companyPhone,username:$username,companyEmail:$companyEmail)}`,variables:{email:form.companyEmail,password:form.password,name:form.adminName,tenantName:form.companyName,companyPhone:form.companyPhone,username:form.username,companyEmail:form.companyEmail}})});const json=await res.json();if(json.errors)throw new Error(json.errors[0].message);const login=await signIn("admin-credentials",{email:form.companyEmail,password:form.password,redirect:false});if(login?.error)throw new Error("Account created, but automatic login failed.");router.push("/dashboard")}catch(err:any){setError(err.message||"Registration failed");setLoading(false)}}
  return <div className="min-h-screen bg-[radial-gradient(circle_at_top,#fff,#F5F5F3_60%,#e9e9e5)] flex items-center justify-center p-4"><div className="w-full max-w-2xl"><div className="text-center mb-7"><div className="mx-auto h-12 w-12 rounded-2xl bg-black text-white flex items-center justify-center font-semibold">LXD</div><h1 className="font-serif text-4xl mt-4">Create company workspace</h1><p className="text-sm text-black/45 mt-2">Set up the administrator profile for your digital attendance system.</p></div><form onSubmit={submit} className="bg-white/90 backdrop-blur rounded-3xl border border-black/5 shadow-2xl p-6 md:p-8 space-y-5">{error&&<div className="p-3 rounded-xl bg-red-50 text-red-700 text-sm">{error}</div>}<div className="grid md:grid-cols-2 gap-4"><Field label="Company Name" value={form.companyName} onChange={v=>set("companyName",v)} required/><Field label="Company Email" type="email" value={form.companyEmail} onChange={v=>set("companyEmail",v)} required/><Field label="Company Phone" value={form.companyPhone} onChange={v=>set("companyPhone",v)} required/><Field label="Admin Name" value={form.adminName} onChange={v=>set("adminName",v)} required/><Field label="Username" value={form.username} onChange={v=>set("username",v)} required/><div/><Field label="Password" type="password" value={form.password} onChange={v=>set("password",v)} required/><Field label="Confirm Password" type="password" value={form.confirmPassword} onChange={v=>set("confirmPassword",v)} required/></div><button disabled={loading} className="w-full h-12 rounded-xl bg-black text-white hover:bg-[#222] transition-colors flex items-center justify-center gap-2 disabled:opacity-50">{loading?<Loader2 className="w-4 h-4 animate-spin"/>:<><span>Create workspace</span><ArrowRight className="w-4 h-4"/></>}</button><p className="text-center text-sm text-black/45">Already registered? <Link href="/login" className="text-black underline underline-offset-4">Sign in</Link></p></form></div></div>
}
function Field({label,value,onChange,type="text",required=false}:{label:string,value:string,onChange:(v:string)=>void,type?:string,required?:boolean}){return <label className="space-y-2 block"><span className="text-[10px] font-mono uppercase tracking-widest text-black/45">{label}</span><input required={required} type={type} value={value} onChange={e=>onChange(e.target.value)} className="w-full h-12 rounded-xl border border-black/10 bg-[#F9F9F8] px-4 text-sm outline-none focus:border-black transition-colors"/></label>}
